# Generated by Django 4.2.4 on 2023-09-04 12:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import nipangeapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('planID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('planName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phoneNo', models.CharField(max_length=15)),
                ('name', models.CharField(default='', max_length=15)),
                ('balance', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('txid', nipangeapp.models.TransactionID(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('txdate', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nipangeapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupID', nipangeapp.models.GroupID(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('groupName', models.CharField(max_length=15)),
                ('users', models.CharField(default=None, max_length=200)),
                ('phone_number', models.CharField(default=None, max_length=15)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nipangeapp.user')),
                ('planId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nipangeapp.plan')),
            ],
        ),
    ]
