# Generated by Django 4.2.4 on 2023-09-08 09:43

from django.db import migrations, models
import django.db.models.deletion
import groups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupid', groups.models.GroupID(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('groupname', models.CharField(max_length=50)),
                ('plan', models.CharField(choices=[('zingatia', 'Zingatia'), ('tugawane', 'tugawane')], default='tugawane', max_length=20)),
                ('groupadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'unique_together': {('phone', 'group')},
            },
        ),
    ]
